name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:      
      - name: SSH into EC2 and create file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /var/www/
            git clone https://${{ secrets.USERNAME }}:${{ secrets.CREDENTIAL }}@github.com/kumarabhishek-github/investorbhaiPackage.git
            cd investorbhaiPackage/ask-me
            npm install
            npm run build
            pm2 restart ask-me || pm2 start npm --name "ask-me" -- start
            
            
